put back check release - where did it go?

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -85,6 +85,12 @@ jobs:
           version: ${{ steps.read_version.outputs.version }}
           path: ./CHANGELOG.md
 
+      - id: check_release
+        run: |
+          TAG=$(git ls-remote --tags origin | grep ${{ steps.read_version.outputs.tag }} | cat )
+          MISSING=$([[ -z "$TAG" ]] && echo 'true' || echo 'false')
+          echo "missing=$MISSING" >> $GITHUB_OUTPUT
+
       - if: ${{ steps.check_release.outputs.missing == 'true' }}
         uses: unsplash/comment-on-pr@master
         env:
